import NavMenu from '@/components/containers/NavMenu/index';
import SessionProvider from '@/components/containers/SessionProvider';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { Inter } from 'next/font/google';
import './globals.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <NavMenu />
          <main className="flex-gap-2 mx-auto max-w-5xl text-2xl">
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
